### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range

### ISSUE THREAD

**Issue by rodney-vin** [futomi/node-sms-pdu#9]
```
const message = 'a'.repeat(200) // 140 bytes User Data per SMS

SmsPDU.generateSubmit('123456', message)

```

It causes Error:
```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 47. Received 48
      at boundsError (internal/buffer.js:83:9)
      at Buffer.readUInt8 (internal/buffer.js:249:5)
      at SmsPduUserDataGsm0338.encode (packages/shonis-sw-a3-vsvw04-b01/node_modules/node-sms-pdu/lib/sms-pdu-user-data-gsm0338.js:418:24)
      at SmsPdu.generateSubmit (packages/shonis-sw-a3-vsvw04-b01/node_modules/node-sms-pdu/lib/sms-pdu.js:98:40)
```

**Comment by rodney-vin** [comment]
The reason is: 
sms-pdu-user-data-gsm0338.js: 384
```
// Set spare bits
      if (rbit_len === 7) {
        // Set to the 7-bit code of the CR control (also used as a padding filler)
        **septet_group.push(0x0D);**
      }
```
Remove this line, will fix this issue. 

And not found others issues when runing regression testing that covers Short SMS and Concatenated SMS
